DapperCodeGenerator.Web/Models/ApplicationState.cs
using System.Collections.Generic;
using DapperCodeGenerator.Core.Enumerations;
using DapperCodeGenerator.Core.Models;
using DapperCodeGenerator.Core.Providers;

namespace DapperCodeGenerator.Web.Models
{
    public class ApplicationState
    {
        public DbConnectionTypes DbConnectionType { get; set; } = DbConnectionTypes.MsSql;
        public string ConnectionString { get; set; } = "";
        public Provider CurrentProvider { get; set; }
        public List<Database> Databases { get; set; } = new List<Database>();
        public Database SelectedDatabase { get; set; }
    }
}

DapperCodeGenerator.Web/Controllers/DatabasesController.cs
using DapperCodeGenerator.Core.Enumerations;
using DapperCodeGenerator.Core.Providers;
using DapperCodeGenerator.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace DapperCodeGenerator.Web.Controllers
{
    public class DatabasesController : Controller
    {
        private readonly ApplicationState _state;

        public DatabasesController(ApplicationState state)
        {
            this._state = state;
        }

        [HttpGet]
        public ActionResult Index()
        {
            UpdateState(DbConnectionTypes.MsSql);

            return View(_state);
        }

        [HttpGet]
        public ActionResult SelectConnectionType(DbConnectionTypes connectionType)
        {
            UpdateState(connectionType);

            return View("Index", _state);
        }

        [HttpGet]
        public ActionResult Refresh(DbConnectionTypes connectionType, string connectionString)
        {
            UpdateState(connectionType, connectionString);

            _state.Databases = _state.CurrentProvider?.RefreshDatabases();

            return View("Index", _state);
        }

        [HttpGet]
        public ActionResult SelectDatabase(string databaseName)
        {
            _state.SelectedDatabase = _state.CurrentProvider?.SelectDatabase(_state.Databases, databaseName);

            return View("Index", _state);
        }

        private void UpdateState(DbConnectionTypes connectionType=DbConnectionTypes.Oracle, string connectionString = null)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
            {
                connectionString = GetDefaultConnectionString(connectionType);
            }

            _state.DbConnectionType = connectionType;
            _state.ConnectionString = connectionString;
            _state.CurrentProvider = GetProvider(connectionType, connectionString);
            _state.Databases = null;
            _state.SelectedDatabase = null;
        }

        private string GetDefaultConnectionString(DbConnectionTypes connectionType=DbConnectionTypes.Oracle)
        {
            switch (connectionType)
            {
                case DbConnectionTypes.MsSql:
                    return "Data Source=localhost;Integrated Security=True;";
                case DbConnectionTypes.Postgres:
                    return "Server=localhost;Port=5432;User Id=postgres;Password=postgres;";
                case DbConnectionTypes.Oracle:
                    return "Data Source=192.168.15.9:1521/ORCL;User Id=MOMS;Password=moms_test_2023;";
                default:
                    return null;
            }
        }

        private Provider GetProvider(DbConnectionTypes connectionType, string connectionString)
        {
            Provider provider;
            switch (connectionType)
            {
                case DbConnectionTypes.MsSql:
                    provider = new MsSqlProvider(connectionString);
                    break;
                case DbConnectionTypes.Postgres:
                    provider = new PostgresProvider(connectionString);
                    break;
                case DbConnectionTypes.Oracle:
                    provider = new OracleProvider(connectionString);
                    break;
                default:
                    return null;
            }

            return provider;
        }
    }
}

DapperCodeGenerator.Web/Views/Databases/Index.cshtml
@using DapperCodeGenerator.Core.Enumerations
@model DapperCodeGenerator.Web.Models.ApplicationState

@{
    ViewBag.Title = "";
    Layout = "_Layout";
}

<form class="mt-3" asp-controller="Databases" asp-action="Refresh" method="get">
    <div class="form-group">
        <label for="connectionType">Connection Type</label>
        <select class="form-control"
                id="connectionType"
                name="connectionType"
                asp-for="DbConnectionType"
                onchange="document.location.href = `/Databases/SelectConnectionType?connectionType=${this.options[this.selectedIndex].value}`;">
            <option>@DbConnectionTypes.MsSql</option>
            <option>@DbConnectionTypes.Postgres</option>
            <option>@DbConnectionTypes.Oracle</option>
        </select>
    </div>
    <div class="form-group">
        <label for="connectionString">Connection String</label>
        <input class="form-control" id="connectionString" name="connectionString" placeholder="@Model.ConnectionString" value="@Model.ConnectionString">
    </div>
    <button type="submit" class="btn btn-primary">Connect</button>
</form>

@if (Model.Databases?.Count == 0)
{
    <div class="mt-5 alert alert-warning" role="alert">
        No databases found. If you know the server you are connecting to has databases, this may be due to an invalid connection string.
    </div>
}

@if (Model.Databases?.Count > 0)
{
    <h3 class="mt-5">Database(s)</h3>

    <select class="form-control"
            id="databaseSelect"
            name="databaseSelect"
            asp-for="SelectedDatabase.DatabaseName"
            asp-items="@(new SelectList(Model.Databases, "DatabaseName", "DatabaseName"))"
            onchange="document.location.href = `/Databases/SelectDatabase?databaseName=${this.options[this.selectedIndex].value}`;">
        <option>Select Database...</option>
    </select>
}

@if (Model.SelectedDatabase != null)
{
    <div class="mt-5">
        <span class="btn-group btn-group-sm float-right">
            <partial name="Partials/DataModels/_GeneratedTablesDataModelsModal" model="Model.SelectedDatabase" />
            <partial name="Partials/Dapper/_GeneratedTablesDapperModal" model="Model.SelectedDatabase" />
        </span>
        <h4><strong>@Model.SelectedDatabase.DatabaseName</strong> Database</h4>
    </div>

    @if (Model.SelectedDatabase.Tables.Count == 0)
    {
        <p>No tables found within <strong>@Model.SelectedDatabase.DatabaseName</strong>. If there are tables, try refreshing.</p>
    }

    <table class="table table-striped table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Table Name</th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 1; i <= Model.SelectedDatabase.Tables.Count; i++)
            {
                var table = Model.SelectedDatabase.Tables[i - 1];

                <tr>
                    <th class="align-middle" scope="row">@i</th>
                    <td>
                        <span class="align-middle">@table.TableName</span>
                        <span class="btn-group btn-group-sm float-right">
                            <partial name="Partials/DataModels/_GeneratedTableDataModelModal" model="table" />
                            <partial name="Partials/Dapper/_GeneratedTableDapperModal" model="table" />
                        </span>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

DapperCodeGenerator.Web/Views/Shared/Partials/Dapper/_GeneratedTableDapperModal.cshtml
@using DapperCodeGenerator.Core.Generators
@model DapperCodeGenerator.Core.Models.DatabaseTable

@{
    var modalId = $"TableDapperModal_{Guid.NewGuid()}";
}

<button type="button" class="btn btn-sm btn-warning" title="@Model.TableName Dapper" data-toggle="modal" data-target="#@modalId">Dapper</button>

<div id="@modalId" class="modal fade" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@Model.DatabaseName Database &gt; <strong>@Model.TableName</strong> Dapper</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-info" role="alert">
                    <label for="alt-generators">Alternatives:</label>
                    <ul id="alt-generators">
                        <li><a href="https://github.com/MoonStorm/Dapper.FastCRUD">FastCRUD</a></li>
                        <li><a href="https://github.com/ericdc1/Dapper.SimpleCRUD">SimpleCRUD</a></li>
                    </ul>
                </div>
                <h5><code id="@modalId-data-model-name">@{@Model.DatabaseName}Repository.cs</code></h5>
                <div class="alert alert-warning" role="alert">
                    This Dapper code is written using T-SQL syntax and might not be compatible with Postgres/Orale
                </div>
                <pre><code id="@modalId-data-model-code">@DapperGeneratorOracle.GenerateDapperFromTable(Model)</code></pre>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

DapperCodeGenerator.Web/Views/Shared/Partials/Dapper/_GeneratedTablesDapperModal.cshtml
@using DapperCodeGenerator.Core.Generators
@model DapperCodeGenerator.Core.Models.Database

@{
    var modalId = $"TablesDapperModal_{Guid.NewGuid()}";
}

<button type="button" class="btn btn-sm btn-warning" title="All @Model.DatabaseName Database Dapper" data-toggle="modal" data-target="#@modalId">All Dapper</button>

<div id="@modalId" class="modal fade" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><strong>@Model.DatabaseName</strong> Database &gt; All Dapper</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-info" role="alert">
                    <label for="alt-generators">Alternatives:</label>
                    <ul id="alt-generators">
                        <li><a href="https://github.com/MoonStorm/Dapper.FastCRUD">FastCRUD</a></li>
                        <li><a href="https://github.com/ericdc1/Dapper.SimpleCRUD">SimpleCRUD</a></li>
                    </ul>
                </div>
                <h5><code id="@modalId-data-model-name">@{@Model.DatabaseName}Repository.cs</code></h5>
                <div class="alert alert-warning" role="alert">
                    This Dapper code is written using T-SQL syntax and might not be compatible with Postgres/Orale
                </div>
                <pre><code id="@modalId-data-model-code">@DapperGeneratorOracle.GenerateDapperFromDatabase(Model)</code></pre>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

DapperCodeGenerator.Web/Views/Shared/Partials/DataModels/_GeneratedTableDataModelModal.cshtml
@using DapperCodeGenerator.Core.Extensions
@using DapperCodeGenerator.Core.Generators
@model DapperCodeGenerator.Core.Models.DatabaseTable

@{
    var modalId = $"DataModelModal_{Guid.NewGuid()}";
}

<button type="button" class="btn btn-sm btn-info" title="@Model.TableName Data Model" data-toggle="modal" data-target="#@modalId">Data Model</button>

<div id="@modalId" class="modal fade" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@Model.DatabaseName Database &gt; <strong>@Model.TableName</strong> Data Model</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Properties</h5>
                <table class="table table-striped table-bordered table-hover">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Column Name</th>
                            <th scope="col">Type</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (var c = 0; c < Model.Columns.Count; c++)
                        {
                            var column = Model.Columns[c];

                            <tr>
                                <th scope="row">@(c + 1)</th>
                                <td>
                                    @column.ColumnName
                                    @if (column.IsPrimaryKey)
                                    {
                                        <i class="material-icons md-18 text-warning align-middle" title="@column.ColumnName is part of the @(string.Join(", ", column.PrimaryKeys)) Primary Key(s) for @column.TableName">vpn_key</i>
                                    }
                                    @if (column.IsForeignKey)
                                    {
                                        <i class="material-icons md-18 text-danger align-middle" title="@column.ColumnName is part of the @(string.Join(", ", column.ForeignKeys)) Foreign Key(s) for @column.TableName">vpn_key</i>
                                    }
                                    @if (column.IsUniqueKey)
                                    {
                                        <i class="material-icons md-18 text-muted align-middle" title="@column.ColumnName is part of the @(string.Join(", ", column.UniqueKeys)) Unique Key(s)/Indexes for @column.TableName">vpn_key</i>
                                    }
                                </td>
                                <td>
                                    @column.Type.GetNameForCoding()
                                    <span class="text-secondary">
                                        <small>
                                            @column.DataType
                                            @if (column.MaxLength > 0)
                                            {
                                                <text>(@column.MaxLength)</text>
                                            }
                                        </small>
                                    </span>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <h5><code id="@modalId-data-model-name">@{@Model.DataModelName}.cs</code></h5>
                <pre><code id="@modalId-data-model-code">@DataModelGenerator.GenerateDataModelFromTable(Model)</code></pre>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

DapperCodeGenerator.Web/Views/Shared/Partials/DataModels/_GeneratedTablesDataModelsModal.cshtml
@using DapperCodeGenerator.Core.Extensions
@using DapperCodeGenerator.Core.Generators
@model DapperCodeGenerator.Core.Models.Database

@{
    var modalId = $"TablesDataModelsModal_{Guid.NewGuid()}";

}

<button type="button" class="btn btn-sm btn-info" title="All @Model.DatabaseName Database Data Models" data-toggle="modal" data-target="#@modalId">All Data Models</button>

<div id="@modalId" class="modal fade" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><strong>@Model.DatabaseName</strong> Database &gt; All Data Models</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <nav class="nav flex-column nav-tabs" id="@modalId-tabs" role="tablist" aria-orientation="vertical">
                        @for (var t = 0; t < Model.Tables.Count; t++)
                        {
                            var table = Model.Tables[t];
                            var tableTabKey = $"{modalId}-{table.TableName.ToLower()}";

                            <a class="nav-link md-18@(t == 0 ? " active" : "")" id="@tableTabKey-tab" data-toggle="tab" href="#@tableTabKey" role="tab" aria-controls="@tableTabKey" aria-selected="@(t == 0 ? "true" : "false")">@table.TableName</a>
                        }
                    </nav>
                    <div class="tab-content" id="@modalId-tabs-content">
                        @for (var t = 0; t < Model.Tables.Count; t++)
                        {
                            var table = Model.Tables[t];
                            var tableTabKey = $"{modalId}-{table.TableName.ToLower()}";

                            <div class="tab-pane fade@(t == 0 ? " show active" : "")" id="@tableTabKey" role="tabpanel" aria-labelledby="@tableTabKey-tab">
                                <h4>@{@table.TableName} Data Model</h4>

                                <table class="table table-striped table-bordered table-hover">
                                    <thead class="thead-light">
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Column Name</th>
                                            <th scope="col">Type</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @for (var c = 0; c < table.Columns.Count; c++)
                                        {
                                            var column = table.Columns[c];

                                            <tr>
                                                <th scope="row">@(c + 1)</th>
                                                <td>
                                                    @column.ColumnName
                                                    @if (column.IsPrimaryKey)
                                                    {
                                                        <i class="material-icons md-18 text-warning align-middle" title="@column.ColumnName is part of the @(string.Join(", ", column.PrimaryKeys)) Primary Key(s) for @column.TableName">vpn_key</i>
                                                    }
                                                    @if (column.IsForeignKey)
                                                    {
                                                        <i class="material-icons md-18 text-danger align-middle" title="@column.ColumnName is part of the @(string.Join(", ", column.ForeignKeys)) Foreign Key(s) for @column.TableName">vpn_key</i>
                                                    }
                                                    @if (column.IsUniqueKey)
                                                    {
                                                        <i class="material-icons md-18 text-muted align-middle" title="@column.ColumnName is part of the @(string.Join(", ", column.UniqueKeys)) Unique Key(s)/Indexes for @column.TableName">vpn_key</i>
                                                    }
                                                </td>
                                                <td>
                                                    @column.Type.GetNameForCoding()
                                                    <span class="text-secondary">
                                                        <small>
                                                            @column.DataType
                                                            @if (column.MaxLength > 0)
                                                            {
                                                                <text>(@column.MaxLength)</text>
                                                            }
                                                        </small>
                                                    </span>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                                <h5><code id="@modalId-data-model-name">@{@table.DataModelName}.cs</code></h5>
                                <pre><code id="@modalId-data-model-code">@DataModelGenerator.GenerateDataModelFromTable(table)</code></pre>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

DapperCodeGenerator.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        Dapper Code Generator
        @{
            var title = ViewData["Title"].ToString();
            if (!string.IsNullOrEmpty(title))
            {
                <text> - </text>@title
            }
        }
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="author" href="humans.txt" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/styles/site.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" id="navbar">
            @*
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-nav" aria-controls="navbar-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            *@
            <a class="navbar-brand" href="/"><b>Dapper Code Generator</b></a>
        </nav>
    </header>

    <div class="container-fluid">
        <div class="row">
            <main role="main" class="col-sm-12 ml-sm-auto">
                <div class="container">
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>

    <small id="footprint"><a href="https://github.com/kcrossman/DapperCodeGenerator">Dapper Code Generator</a> by <b>Kody Crossman</b></small>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/scripts/site.js"></script>
</body>
</html>